"""
Django settings for AnsbOps project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import djcelery
from celery.schedules import crontab
djcelery.setup_loader()
# 允许的格式

BROKER_URL = 'amqp://admin:admin@192.168.145.128//'    #配置broker

# 使用django-celery默认的数据库调度模型,任务执行周期都被存在你指定的orm数据库中
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
#使用rabbitmq作为数据存储
#CELERY_RESULT_BACKEND = 'amqp://admin:admin@192.168.145.128//'
CELERY_TIMEZONE='Asia/Shanghai'  #并没有北京时区，与下面TIME_ZONE应该一致
CELERY_ENABLE_UTC = True
#celery 结果有效期
CELERY_TASK_RESULT_EXPIRES  = 3600
#celery 结果有效期



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u_o%37^itif!2!a3x8gwbcmp3=d0*c$1we5f5$3#!g$2^stozg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery',
    'apps.rbac',
    'apps.cmdb',
    'apps.sysmg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#自定义登录认证中间件
AUTHENTICATION_BACKENDS = (
    'apps.rbac.authviews.CustomBackend',
)


ROOT_URLCONF = 'AnsbOps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AnsbOps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "AnsbOps",
        "HOST":"192.168.145.128",
        "USER":"root",
        "PASSWORD":"Oneday@2019",
        "PORT":3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#登录认证url
LOGIN_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

#静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'statics')]

#静态文件配置
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'statics')]

#加密字符串
ENCRYPT_KEY = "ajfo38fja09*&014"

MEDIA_ROOT = os.path.join(BASE_DIR,'medias')
MEDIA_URL = '/media/'

#登录认证url
SESSION_SAVE_EVERY_REQUEST = True
# 关闭浏览器，则COOKIE失效
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#30分钟
SESSION_COOKIE_AGE = 60 * 60 * 24

#zabbix api 参数配置
ZABBIX_URL = 'http://115.231.100.246:18080/zabbix/api_jsonrpc.php'
ZABBIX_USER = "admin"
ZABBIX_PASS = "zabbix"

#redis配置
#redis 服务信息
REDIS_HOST = "192.168.145.128"
REDIS_PORT =6379


#定时任务
CELERYBEAT_SCHEDULE = {
    u'每分3钟获取一次zabbix告警信息': {
        "task": "apps.rbac.tasks.get_zabbix_groblem",
        "schedule": crontab(minute='*/3'),
        "args": (ZABBIX_URL, ZABBIX_USER, ZABBIX_PASS),
    },
    u'每天凌晨0点同步服务器信息': {
        "task": "apps.cmdb.tasks.sync_os_info",
        "schedule": crontab(minute=30,hour=0),
        "args": (),
    },
}







